$"abc"
$""
$"abc with ""quotes"" and {{ and }}"
$"abc with {id_1} and {id_2}"
$"abc with {id}"
$"{id} with abc"
$"{id_1} and {id_2}"
$"{id_1}{id_2}"
$"{$"{id}"}"
$"{$"{$"{id}"}"}"
$"{$"{id_1}"} and {$"{id2}"}"
$"Result = {If(value = 1, "one", "other")}"
$"{foo.Bar.Baz}"
$"{arr(i + 1)}"
$"{If(x, $"yes {name}", "no")}"
$"{{ {value} }}"
$"{SomeMethod("}")}"
$"{If(x = 1, "{test}", "{other}")}"

$"""
$"abc
$"
$"{"
$"}"
